### ISSUE TITLE
Exception for IP addresses without AbuseIPDB entry

### ISSUE THREAD

**Issue by PeterJ2** [actually-akac/AbuseIPDB#1]
I've noticed when `Check()` is called for an IP address that's not in the AbuseIPDB  database the following exception is thrown:

> Exception while parsing JSON: JsonException => The JSON value could not be converted to System.Boolean. Path: $.data.isWhitelisted | LineNumber: 0 | BytePositionInLine: 87.

It's easy enough to catch but perhaps a better behavior would either be returning an empty `CheckedIP` result or throwing a more specific exception.

**Comment by akacdev** [comment]
Hey, thank you for taking the time to bring this issue to my attention.

I've identified the source of this and released a fix in version `1.2.3` (https://github.com/actually-akac/AbuseIPDB/commit/205c0ea412737d1e5eb962465965b0c73ab75c9c). You should see the expected behavior after updating.

There was an issue with JSON parsing due to unexpected `null` properties being returned from the API. I've forgotten to mark some properties as nullable.

In order to check whether an IP address has never been reported, you may use the `CheckedIP.LastReportedAt` property, which is now `null` in cases of unreported IP addresses. Both `CheckedIP.TotalReports` and `CheckedIP.DistinctUserCount` depend on reports within the max age period (by default 90 days), so they may not be accurate if you want to filter IP addresses that have ever been reported.

If there are any other concerns you have, don't hesitate to open another issue.
